/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pdieditor;

import javax.media.jai.*;
import javax.swing.*;

/**
 *
 * @author Caio
 */
public class Segmentacao extends javax.swing.JFrame {

    /**
     * Creates new form Limiarizacao
     */
    public Segmentacao() {
        initComponents();
    }

    Segmentacao(JanelaPrincipal aThis) {
        initComponents();
        ref = aThis;
        PlanarImage pi = ref.imagemAtual();
        Histogram h = Util.histograma(pi);
        PlanarImage gi = Util.gerarGrafico(h);
        displayImagem.set(gi);
        iterativo = (int)Math.round(h.getIterativeThreshold()[0]);
        otsu = (int)Math.round(h.getMaxVarianceThreshold()[0]);
        rErro = (int)Math.round(h.getMinErrorThreshold()[0]);
        entropia = (int)Math.round(h.getMaxEntropyThreshold()[0]);
        rFuzz = (int)Math.round(h.getMinFuzzinessThreshold()[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        deslizanteCor = new javax.swing.JSlider();
        valorCor = new javax.swing.JLabel();
        textoCor = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        displayImagem = new com.sun.media.jai.widget.DisplayJAI();
        radioManual = new javax.swing.JRadioButton();
        radioIterativo = new javax.swing.JRadioButton();
        radioOtsu = new javax.swing.JRadioButton();
        radioEntropia = new javax.swing.JRadioButton();
        radioRFuzz = new javax.swing.JRadioButton();
        radioRErro = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deslizanteCor.setMaximum(254);
        deslizanteCor.setMinimum(1);
        deslizanteCor.setValue(127);
        deslizanteCor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizanteCorStateChanged(evt);
            }
        });

        valorCor.setText("127");

        textoCor.setText("Cor:");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        displayImagem.setBackground(new java.awt.Color(255, 255, 255));
        displayImagem.setPreferredSize(new java.awt.Dimension(1500, 750));

        grupoRadio.add(radioManual);
        radioManual.setSelected(true);
        radioManual.setText("Manual");
        radioManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioManualActionPerformed(evt);
            }
        });

        grupoRadio.add(radioIterativo);
        radioIterativo.setText("Iterativo");
        radioIterativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIterativoActionPerformed(evt);
            }
        });

        grupoRadio.add(radioOtsu);
        radioOtsu.setText("Otsu");
        radioOtsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOtsuActionPerformed(evt);
            }
        });

        grupoRadio.add(radioEntropia);
        radioEntropia.setText("Por entropia");
        radioEntropia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEntropiaActionPerformed(evt);
            }
        });

        grupoRadio.add(radioRFuzz);
        radioRFuzz.setText("Reduzir fuzziness");
        radioRFuzz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRFuzzActionPerformed(evt);
            }
        });

        grupoRadio.add(radioRErro);
        radioRErro.setText("Reduzir erro");
        radioRErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRErroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayImagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(radioManual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioIterativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioOtsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioEntropia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioRFuzz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioRErro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoCor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deslizanteCor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorCor)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deslizanteCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorCor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoCor)
                        .addComponent(radioRErro)
                        .addComponent(radioRFuzz)
                        .addComponent(radioEntropia)
                        .addComponent(radioOtsu)
                        .addComponent(radioIterativo)
                        .addComponent(radioManual)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(ok))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        PlanarImage pi = ref.imagemAtual();
        if(pi != null) {
            PlanarImage ti = Util.segmentar(pi, cor);
            if(ti != null) {
                ref.atualizarImagem(ti);
                dispose();
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Não foi possível filtrar a imagem!", "Erro na imagem", JOptionPane.ERROR_MESSAGE);
        dispose();
    }//GEN-LAST:event_okActionPerformed

    private void deslizanteCorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizanteCorStateChanged
        cor = deslizanteCor.getValue();
        valorCor.setText(Integer.toString(cor));
    }//GEN-LAST:event_deslizanteCorStateChanged

    private void radioIterativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIterativoActionPerformed
        cor = iterativo;
        deslizanteCor.setValue(cor);
        deslizanteCor.setEnabled(false);
        valorCor.setText(Integer.toString(cor));
    }//GEN-LAST:event_radioIterativoActionPerformed

    private void radioOtsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOtsuActionPerformed
        cor = otsu;
        deslizanteCor.setValue(cor);
        deslizanteCor.setEnabled(false);
        valorCor.setText(Integer.toString(cor));
    }//GEN-LAST:event_radioOtsuActionPerformed

    private void radioEntropiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEntropiaActionPerformed
        cor = entropia;
        deslizanteCor.setValue(cor);
        deslizanteCor.setEnabled(false);
        valorCor.setText(Integer.toString(cor));
    }//GEN-LAST:event_radioEntropiaActionPerformed

    private void radioRFuzzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRFuzzActionPerformed
        cor = rFuzz;
        deslizanteCor.setValue(cor);
        deslizanteCor.setEnabled(false);
        valorCor.setText(Integer.toString(cor));
    }//GEN-LAST:event_radioRFuzzActionPerformed

    private void radioRErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRErroActionPerformed
        cor = rErro;
        deslizanteCor.setValue(cor);
        deslizanteCor.setEnabled(false);
        valorCor.setText(Integer.toString(cor));
    }//GEN-LAST:event_radioRErroActionPerformed

    private void radioManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioManualActionPerformed
        deslizanteCor.setEnabled(true);
    }//GEN-LAST:event_radioManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Segmentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Segmentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JSlider deslizanteCor;
    private com.sun.media.jai.widget.DisplayJAI displayImagem;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.JButton ok;
    private javax.swing.JRadioButton radioEntropia;
    private javax.swing.JRadioButton radioIterativo;
    private javax.swing.JRadioButton radioManual;
    private javax.swing.JRadioButton radioOtsu;
    private javax.swing.JRadioButton radioRErro;
    private javax.swing.JRadioButton radioRFuzz;
    private javax.swing.JLabel textoCor;
    private javax.swing.JLabel valorCor;
    // End of variables declaration//GEN-END:variables
    private JanelaPrincipal ref = null;
    private int cor = 127;
    private int iterativo = cor;
    private int otsu = cor;
    private int rErro = cor;
    private int entropia = cor;
    private int rFuzz = cor;
}
